import { themeQuartz } from 'ag-grid-community';

export const marketsUITheme = themeQuartz
  .withParams(
    {
      accentColor: '#60A5FA',
      backgroundColor: '#ffffff',
      foregroundColor: '#1A1A1A',
      headerBackgroundColor: '#ffffff',
      headerTextColor: '#6F7177',
      headerFontSize: 10,
      borderColor: '#E0E0E0',
      borderRadius: 8,
      rowHoverColor: '#EBEBEB',
      selectedRowBackgroundColor: 'rgba(96, 165, 250, 0.06)',
      fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
      fontSize: 11,
      rowHeight: 36,
      headerHeight: 30,
      wrapperBorderRadius: 8,
      cellHorizontalPaddingScale: 0.7,
      browserColorScheme: 'light' as const,
      checkboxCheckedBackgroundColor: '#60A5FA',
      checkboxCheckedBorderColor: '#60A5FA',
      checkboxCheckedShapeColor: '#ffffff',
      inputFocusBorder: '#60A5FA',
      inputFocusShadow: '0 0 0 3px rgba(96, 165, 250, 0.2)',
      sideBarBackgroundColor: '#ffffff',
      sideButtonSelectedBackgroundColor: '#EBEBEB',
      columnDropCellBackgroundColor: '#EBEBEB',
      toggleButtonOnBackgroundColor: '#60A5FA',
      rangeSelectionBorderColor: '#60A5FA',
      rangeSelectionBackgroundColor: 'rgba(96, 165, 250, 0.08)',
      modalOverlayBackgroundColor: 'rgba(26, 26, 26, 0.4)',
      cardShadow: '0 1px 3px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02)',
    },
    'light'
  )
  .withParams(
    {
      accentColor: '#60A5FA',
      backgroundColor: '#1A1D21',
      foregroundColor: '#FFFFFF',
      headerBackgroundColor: '#1A1D21',
      headerTextColor: '#9DA0A5',
      headerFontSize: 10,
      borderColor: '#2C2F33',
      borderRadius: 8,
      rowHoverColor: 'rgba(36, 39, 41, 0.8)',
      selectedRowBackgroundColor: 'rgba(96, 165, 250, 0.08)',
      fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
      fontSize: 11,
      rowHeight: 36,
      headerHeight: 30,
      wrapperBorderRadius: 8,
      cellHorizontalPaddingScale: 0.7,
      browserColorScheme: 'dark' as const,
      checkboxCheckedBackgroundColor: '#60A5FA',
      checkboxCheckedBorderColor: '#60A5FA',
      checkboxCheckedShapeColor: '#ffffff',
      checkboxUncheckedBorderColor: '#2C2F33',
      inputFocusBorder: '#60A5FA',
      inputFocusShadow: '0 0 0 3px rgba(96, 165, 250, 0.25)',
      sideBarBackgroundColor: '#1A1D21',
      sideButtonSelectedBackgroundColor: '#242729',
      columnDropCellBackgroundColor: '#1E2124',
      toggleButtonOnBackgroundColor: '#60A5FA',
      rangeSelectionBorderColor: '#60A5FA',
      rangeSelectionBackgroundColor: 'rgba(96, 165, 250, 0.1)',
      modalOverlayBackgroundColor: 'rgba(0, 0, 0, 0.5)',
      cardShadow: '0 1px 3px rgba(0, 0, 0, 0.2), 0 1px 2px rgba(0, 0, 0, 0.12)',
    },
    'dark'
  );
